# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostOfProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('years', models.PositiveSmallIntegerField()),
                ('annualInterestRate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('capEx', models.DecimalField(decimal_places=2, max_digits=14)),
                ('areasServiced', models.PositiveSmallIntegerField()),
                ('otherCapEx', models.DecimalField(decimal_places=2, max_digits=14)),
                ('opEx', models.DecimalField(decimal_places=2, max_digits=14)),
                ('otherOpEx', models.DecimalField(decimal_places=2, max_digits=14)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRC.AssessmentType')),
            ],
        ),
        migrations.CreateModel(
            name='DamageAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('damageToValueRiskRatio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('additionalEscalationDamages', models.DecimalField(decimal_places=2, max_digits=14)),
                ('adjustmentForSecondaryLosses', models.DecimalField(decimal_places=2, max_digits=4)),
                ('annualPlantBIEValue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fullProductionDaysLost', models.PositiveSmallIntegerField()),
                ('additionalDaysLost', models.PositiveSmallIntegerField()),
                ('indirectOrPartialLoss', models.DecimalField(decimal_places=2, max_digits=14)),
                ('otherBIELosses', models.DecimalField(decimal_places=2, max_digits=14)),
                ('thirdPartyPlume', models.DecimalField(decimal_places=2, max_digits=14)),
                ('disposalOfMEOH', models.DecimalField(decimal_places=2, max_digits=14)),
                ('shareholderPartnerRelationship', models.DecimalField(decimal_places=2, max_digits=14)),
                ('customerGoodwill', models.DecimalField(decimal_places=2, max_digits=14)),
                ('managementTime', models.DecimalField(decimal_places=2, max_digits=14)),
                ('riskToEmergPersonnel', models.DecimalField(decimal_places=2, max_digits=14)),
                ('otherOLLosses', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('basis', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('freq', models.DecimalField(decimal_places=8, max_digits=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='ProbabilityOfLoss',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='IRC.CaseSetup')),
                ('freq', models.DecimalField(decimal_places=8, max_digits=8)),
                ('siteHistoryAndAge', models.DecimalField(decimal_places=2, max_digits=3)),
                ('serviceAndEnvironment', models.DecimalField(decimal_places=2, max_digits=3)),
                ('levelOfPMAndOperatorXP', models.DecimalField(decimal_places=2, max_digits=3)),
                ('accessToERAndFirstResponse', models.DecimalField(decimal_places=2, max_digits=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('protection', models.ManyToManyField(to='IRC.CostOfProtection')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRC.Site'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damageassessment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRC.CaseSetup'),
        ),
        migrations.AddField(
            model_name='casesetup',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRC.Site'),
        ),
        migrations.AddField(
            model_name='casesetup',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRC.AssessmentType'),
        ),
        migrations.AddField(
            model_name='casesetup',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRC.Unit'),
        ),
    ]
