# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_BIE_addProdDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_BIE_annBIEValue_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_BIE_directBILoss_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_BIE_fullProdDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_BIE_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_BIE_totalBIE_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_BIE_totalDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_amortizedCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_annualCOP_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_arealCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_areasServiced_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_capExTotal_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_opEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_otherCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_otherOpEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_residualPV_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_residual_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_COP_totalCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_OL_MEOHDisposal_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_OL_customerShippingGoodwill_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_OL_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_OL_emergPersonnelRisk_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_OL_mgmtTime_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_OL_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_OL_shareholderPartnerRel_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_OL_smokePlume_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PDA_addDmgs_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PDA_adjFactor_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PDA_dmgFactor_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PDA_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PDA_subTotalDmgs_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PDA_total_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PDA_valueAtRisk_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PL_adjCopy_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PL_adjFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PL_baseFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PL_freq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_BIE_addProdDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_BIE_annBIEValue_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_BIE_directBILoss_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_BIE_fullProdDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_BIE_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_BIE_totalBIE_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_BIE_totalDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_amortizedCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_annualCOP_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_arealCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_areasServiced_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_capExTotal_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_opEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_otherCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_otherOpEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_residualPV_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_residual_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_COP_totalCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_OL_MEOHDisposal_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_OL_customerShippingGoodwill_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_OL_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_OL_emergPersonnelRisk_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_OL_mgmtTime_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_OL_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_OL_shareholderPartnerRel_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_OL_smokePlume_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PDA_addDmgs_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PDA_adjFactor_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PDA_dmgFactor_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PDA_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PDA_subTotalDmgs_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PDA_total_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PDA_valueAtRisk_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PL_adjCopy_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PL_adjFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PL_baseFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PL_freq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_BIE_addProdDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_BIE_annBIEValue_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_BIE_directBILoss_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_BIE_fullProdDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_BIE_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_BIE_totalBIE_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_BIE_totalDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_amortizedCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_annualCOP_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_arealCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_areasServiced_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_capExTotal_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_opEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_otherCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_otherOpEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_residualPV_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_residual_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_COP_totalCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_OL_MEOHDisposal_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_OL_customerShippingGoodwill_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_OL_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_OL_emergPersonnelRisk_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_OL_mgmtTime_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_OL_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_OL_shareholderPartnerRel_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_OL_smokePlume_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_addDmgs_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_adjFactor_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_dmgFactor_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_subTotalDmgs_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_total_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_valueAtRisk_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_adjCopy_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_adjFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_baseFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_freq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_BIE_addProdDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_BIE_annBIEValue_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_BIE_directBILoss_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_BIE_fullProdDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_BIE_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_BIE_totalBIE_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_BIE_totalDaysLost_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_amortizedCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_annualCOP_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_arealCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_areasServiced_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_capExTotal_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_opEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_otherCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_otherOpEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_residualPV_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_residual_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_COP_totalCapEx_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_OL_MEOHDisposal_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_OL_customerShippingGoodwill_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_OL_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_OL_emergPersonnelRisk_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_OL_mgmtTime_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_OL_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_OL_shareholderPartnerRel_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_OL_smokePlume_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PDA_addDmgs_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PDA_adjFactor_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PDA_dmgFactor_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PDA_other_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PDA_subTotalDmgs_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PDA_total_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PDA_valueAtRisk_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PL_adjCopy_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PL_adjFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PL_baseFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PL_freq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
