# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageAssessmentCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init', models.PositiveSmallIntegerField()),
                ('curVal', models.SmallIntegerField()),
            ],
        ),
    ]
