# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRC', '0002_auto_20170720_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardassessment',
            name='summary_Ass',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='standardassessment',
            name='summary_CaseDesc',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardassessment',
            name='summary_Conc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='standardassessment',
            name='summary_F',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='standardassessment',
            name='summary_FM',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='standardassessment',
            name='summary_L',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='standardassessment',
            name='summary_M',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='standardassessment',
            name='summary_Results',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
