# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRC', '0002_damageassessmentcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageassessmentcounter',
            name='probLoss',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='IRC.ProbabilityOfLoss'),
        ),
    ]
