# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRC', '0003_auto_20170721_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardassessment',
            name='summary_Ass',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='summary_CaseDesc',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='summary_Conc',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='summary_F',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='summary_FM',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='summary_L',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='summary_M',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='summary_Results',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
