# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRC', '0004_auto_20170722_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_adjCopy',
            field=models.PositiveIntegerField(verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_adjFreq',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_adjFreq_desc',
            field=models.TextField(blank=True, max_length=200, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_baseFreq',
            field=models.DecimalField(decimal_places=9, max_digits=9, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_baseFreq_desc',
            field=models.TextField(blank=True, max_length=200, verbose_name='X'),
        ),
    ]
