# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRC', '0005_auto_20170722_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PL_adjFreq',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PL_baseFreq',
            field=models.DecimalField(decimal_places=9, max_digits=9, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='FM_PL_freq',
            field=models.DecimalField(decimal_places=9, max_digits=9, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PL_adjCopy',
            field=models.PositiveIntegerField(verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PL_adjFreq',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PL_baseFreq',
            field=models.DecimalField(decimal_places=9, max_digits=9, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='F_PL_freq',
            field=models.DecimalField(decimal_places=9, max_digits=9, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_addDmgs',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_adjFactor',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_dmgFactor',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_other',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_subTotalDmgs',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PDA_valueAtRisk',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_adjFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_baseFreq_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='L_PL_freq',
            field=models.DecimalField(decimal_places=9, max_digits=9, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PL_adjFreq',
            field=models.DecimalField(decimal_places=3, max_digits=4, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PL_baseFreq',
            field=models.DecimalField(decimal_places=9, max_digits=9, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='standardassessment',
            name='M_PL_freq',
            field=models.DecimalField(decimal_places=9, max_digits=9, verbose_name='X'),
        ),
    ]
